### ISSUE TITLE
Correctly detect POW/POP payouts 

### ISSUE THREAD

**Issue by Warchant** [VeriBlock/vbk-ri-btc-explorer#6]
https://github.com/VeriBlock/vbk-ri-btc-explorer/blob/master/views/includes/transaction-io-details.pug#L198
We no longer have last vout as "pop root"

**Comment by Mr-Leshiy** [comment]
Unfortunately it is not possible to somehow correctly define which reward is PoW/PoP.

**Comment by Warchant** [comment]
Then remove "POP" tooltip
